# Generated by Django 5.2.4 on 2025-07-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('potencial', 'Potencial'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='potencial', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comercial asignado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Email'), ('reunion', 'Reunión'), ('visita', 'Visita')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('duration', models.IntegerField(default=0, help_text='Duración en minutos', verbose_name='Duración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
