# Generated by Django 4.2.7 on 2025-08-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
    ]
